package com.lre_server.entity;

import java.util.Date;

public class SessionInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..session_info.session_id
     *
     * @mbg.generated
     */
    private String sessionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..session_info.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..session_info.session_content
     *
     * @mbg.generated
     */
    private String sessionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..session_info.lre_result
     *
     * @mbg.generated
     */
    private Byte lreResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..session_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..session_info.session_id
     *
     * @return the value of lre_server..session_info.session_id
     *
     * @mbg.generated
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..session_info.session_id
     *
     * @param sessionId the value for lre_server..session_info.session_id
     *
     * @mbg.generated
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..session_info.client_id
     *
     * @return the value of lre_server..session_info.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..session_info.client_id
     *
     * @param clientId the value for lre_server..session_info.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..session_info.session_content
     *
     * @return the value of lre_server..session_info.session_content
     *
     * @mbg.generated
     */
    public String getSessionContent() {
        return sessionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..session_info.session_content
     *
     * @param sessionContent the value for lre_server..session_info.session_content
     *
     * @mbg.generated
     */
    public void setSessionContent(String sessionContent) {
        this.sessionContent = sessionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..session_info.lre_result
     *
     * @return the value of lre_server..session_info.lre_result
     *
     * @mbg.generated
     */
    public Byte getLreResult() {
        return lreResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..session_info.lre_result
     *
     * @param lreResult the value for lre_server..session_info.lre_result
     *
     * @mbg.generated
     */
    public void setLreResult(Byte lreResult) {
        this.lreResult = lreResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..session_info.create_time
     *
     * @return the value of lre_server..session_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..session_info.create_time
     *
     * @param createTime the value for lre_server..session_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}