package com.lre_server.entity;

import java.util.Date;

public class SysRole extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..sys_role.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..sys_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..sys_role.create_user_id
     *
     * @mbg.generated
     */
    private Integer createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..sys_role.role_info
     *
     * @mbg.generated
     */
    private String roleInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..sys_role.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..sys_role.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..sys_role.role_id
     *
     * @return the value of lre_server..sys_role.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..sys_role.role_id
     *
     * @param roleId the value for lre_server..sys_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..sys_role.role_name
     *
     * @return the value of lre_server..sys_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..sys_role.role_name
     *
     * @param roleName the value for lre_server..sys_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..sys_role.create_user_id
     *
     * @return the value of lre_server..sys_role.create_user_id
     *
     * @mbg.generated
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..sys_role.create_user_id
     *
     * @param createUserId the value for lre_server..sys_role.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..sys_role.role_info
     *
     * @return the value of lre_server..sys_role.role_info
     *
     * @mbg.generated
     */
    public String getRoleInfo() {
        return roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..sys_role.role_info
     *
     * @param roleInfo the value for lre_server..sys_role.role_info
     *
     * @mbg.generated
     */
    public void setRoleInfo(String roleInfo) {
        this.roleInfo = roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..sys_role.create_time
     *
     * @return the value of lre_server..sys_role.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..sys_role.create_time
     *
     * @param createTime the value for lre_server..sys_role.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..sys_role.update_time
     *
     * @return the value of lre_server..sys_role.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..sys_role.update_time
     *
     * @param updateTime the value for lre_server..sys_role.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}