package com.lre_server.entity;

import java.util.Date;

public class UserClient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.client_id
     *
     * @mbg.generated
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.client_type
     *
     * @mbg.generated
     */
    private Byte clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.client_OS
     *
     * @mbg.generated
     */
    private Byte clientOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.client_info
     *
     * @mbg.generated
     */
    private String clientInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lre_server..user_client.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.client_id
     *
     * @return the value of lre_server..user_client.client_id
     *
     * @mbg.generated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.client_id
     *
     * @param clientId the value for lre_server..user_client.client_id
     *
     * @mbg.generated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.user_id
     *
     * @return the value of lre_server..user_client.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.user_id
     *
     * @param userId the value for lre_server..user_client.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.client_name
     *
     * @return the value of lre_server..user_client.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.client_name
     *
     * @param clientName the value for lre_server..user_client.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.client_type
     *
     * @return the value of lre_server..user_client.client_type
     *
     * @mbg.generated
     */
    public Byte getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.client_type
     *
     * @param clientType the value for lre_server..user_client.client_type
     *
     * @mbg.generated
     */
    public void setClientType(Byte clientType) {
        this.clientType = clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.client_OS
     *
     * @return the value of lre_server..user_client.client_OS
     *
     * @mbg.generated
     */
    public Byte getClientOs() {
        return clientOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.client_OS
     *
     * @param clientOs the value for lre_server..user_client.client_OS
     *
     * @mbg.generated
     */
    public void setClientOs(Byte clientOs) {
        this.clientOs = clientOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.client_info
     *
     * @return the value of lre_server..user_client.client_info
     *
     * @mbg.generated
     */
    public String getClientInfo() {
        return clientInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.client_info
     *
     * @param clientInfo the value for lre_server..user_client.client_info
     *
     * @mbg.generated
     */
    public void setClientInfo(String clientInfo) {
        this.clientInfo = clientInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.status
     *
     * @return the value of lre_server..user_client.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.status
     *
     * @param status the value for lre_server..user_client.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lre_server..user_client.create_time
     *
     * @return the value of lre_server..user_client.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lre_server..user_client.create_time
     *
     * @param createTime the value for lre_server..user_client.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}