package com.lre_server.dao;

import com.lre_server.entity.FileInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface FileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..file_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..file_info
     *
     * @mbg.generated
     */
    int insert(FileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..file_info
     *
     * @mbg.generated
     */
    FileInfo selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..file_info
     *
     * @mbg.generated
     */
    List<FileInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..file_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileInfo record);

    List<FileInfo> fileInfoList();
}