package com.lre_server.dao;

import com.lre_server.entity.SessionInfo;
import java.util.List;

public interface SessionInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..session_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..session_info
     *
     * @mbg.generated
     */
    int insert(SessionInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..session_info
     *
     * @mbg.generated
     */
    SessionInfo selectByPrimaryKey(String sessionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..session_info
     *
     * @mbg.generated
     */
    List<SessionInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..session_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SessionInfo record);
}