package com.lre_server.dao;

import com.lre_server.entity.SysUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..sys_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..sys_user
     *
     * @mbg.generated
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..sys_user
     *
     * @mbg.generated
     */
    SysUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..sys_user
     *
     * @mbg.generated
     */
    List<SysUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lre_server..sys_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUser record);

    /**
     * 根据用户名查询用户信息
     * @param userName
     * @return
     */
    SysUser selectByUserName(String userName);

    /**
     * 查询用户列表
     * @return
     */
    List<SysUser> selectUserList(@Param(value = "sysUser") SysUser sysUser);
}